#!/bin/bash
#====================================================
#	SCRIPT: SSHPLUS MANAGER CREATE USER ACCOUNT
#	TRANSLATED BY:	JENBHIE
#====================================================
IP=$(cat /etc/IP)
cor1='\033[41;1;37m'
cor2='\033[44;1;37m'
scor='\033[0m'
# Generate client.ovpn
newclient() {
    cp /etc/openvpn/client-common.txt ~/$1.ovpn
    echo "<ca>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/ca.crt >>~/$1.ovpn
    echo "</ca>" >>~/$1.ovpn
    echo "<cert>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >>~/$1.ovpn
    echo "</cert>" >>~/$1.ovpn
    echo "<key>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/private/$1.key >>~/$1.ovpn
    echo "</key>" >>~/$1.ovpn
    echo "<tls-auth>" >>~/$1.ovpn
    cat /etc/openvpn/ta.key >>~/$1.ovpn
    echo "</tls-auth>" >>~/$1.ovpn
}
fun_geraovpn() {
    [[ "$respost" = @(s|S) ]] && {
        cd /etc/openvpn/easy-rsa/
        sudo ./easyrsa build-client-full $username nopass
        newclient "$username"
        sed -e "s;auth-user-pass;<auth-user-pass>\n$username\n$password\n</auth-user-pass>;g" /root/$username.ovpn >/root/tmp.ovpn && mv -f /root/tmp.ovpn /root/$username.ovpn
    } || {
        cd /etc/openvpn/easy-rsa/
        sudo ./easyrsa build-client-full $username nopass
        newclient "$username"
    }
} >/dev/null 2>&1
[[ -e /etc/openvpn/server.conf ]] && {
    _Port=$(grep -w 'port' /etc/openvpn/server.conf | awk {'print $2'})
    hst=$(sed -n '8 p' /etc/openvpn/client-common.txt | awk {'print $4'})
    rmt=$(sed -n '7 p' /etc/openvpn/client-common.txt)
    hedr=$(sed -n '8 p' /etc/openvpn/client-common.txt)
    prxy=$(sed -n '9 p' /etc/openvpn/client-common.txt)
    rmt2='/SSHPLUS?'
    rmt3='www.vivo.com.br 8088'
    prx='200.142.130.104'
    payload1='#payload "HTTP/1.0 [crlf]Host: m.youtube.com[crlf]CONNECT HTTP/1.0[crlf][crlf]|[crlf]"'
    payload2='#payload "CONNECT 127.0.0.1:1194[split][crlf] HTTP/1.0 [crlf][crlf]#"'
    vivo1="portalrecarga.vivo.com.br/recarga"
    vivo2="portalrecarga.vivo.com.br/controle/"
    vivo3="navegue.vivo.com.br/pre/"
    vivo4="navegue.vivo.com.br/controle/"
    vivo5="www.vivo.com.br"
    oi="d1n212ccp6ldpw.cloudfront.net"
    bypass="net_gateway"
    cert01="/etc/openvpn/client-common.txt"
    if [[ "$hst" == "$vivo1" ]]; then
        Host="Portal Recharge"
    elif [[ "$hst" == "$vivo2" ]]; then
        Host="Recharge Control"
    elif [[ "$hst" == "$vivo3" ]]; then
        Host="Portal Browse"
    elif [[ "$hst" == "$vivo4" ]]; then
        Host="Nav control"
    elif [[ "$hst" == "$IP:$_Port" ]]; then
        Host="Vivo MMS"
    elif [[ "$hst" == "$oi" ]]; then
        Host="Oi"
    elif [[ "$hst" == "$bypass" ]]; then
        Host="Bypass mode"
    elif [[ "$hedr" == "$payload1" ]]; then
        Host="OPEN SOCKS"
    elif [[ "$hedr" == "$payload2" ]]; then
        Host="OPEN SQUID"
    else
        Host="Customized"
    fi
}
fun_bar() {
    command[0]="$1"
    command[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${command[0]} >/dev/null 2>&1
        ${command[1]} >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "\033[1;33mWAIT \033[1;37m- \033[1;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;31m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[1;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[1;33mWAIT \033[1;37m- \033[1;33m["
    done
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
fun_edithost() {
    clear
    echo -e "\E[44;1;37m          CHANGE OVPN HOST            \E[0m"
    echo ""
    echo -e "\033[1;33mHOST IN USE\033[1;37m: \033[1;32m$Host"
    echo ""
    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mLIVE RECHARGE"
    echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mLIVE NAVIGATOR"
    echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;33mOPEN SOCKS \033[1;31m[\033[1;32mAPP MOD\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;33mOPEN SQUID \033[1;31m[\033[1;32mAPP MOD\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;33mVIVO MMS \033[1;31m[\033[1;37mAPN: \033[1;32mmms.vivo.com.br\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;33mBYPASS MODE \033[1;31m[\033[1;32mOPEN + INJECTOR\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m7\033[1;31m] \033[1;33mALL HOSTS \033[1;31m[\033[1;32m1 OF EACH OVPN\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m8\033[1;31m] \033[1;33mEDIT MANUALLY"
    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;33mBACK"
    echo ""
    echo -ne "\033[1;32mWHICH HOST YOU WANT TO USE \033[1;33m?\033[1;37m "
    read respo
    [[ -z "$respo" ]] && {
        echo -e "\n\033[1;31mInvalid option!"
        sleep 2
        fun_edithost
    }
    if [[ "$respo" = '1' ]]; then
        echo -e "\n\033[1;32mCHANGING HOST!\033[0m\n"
        fun_althost() {
            sudo sed -i "s;$rmt;remote $rmt2 $_Port;" $cert01
            sudo sed -i "s;$hedr;http-proxy-option CUSTOM-HEADER Host $vivo1;" $cert01
            sudo sed -i "s;$prxy;http-proxy $IP 80;" $cert01
        }
        fun_bar 'fun_althost'
        echo -e "\n\033[1;32mHOST CHANGED SUCCESSFULLY!\033[0m"
        fun_geraovpn
        sleep 1.5
    elif [[ "$respo" = '2' ]]; then
        echo -e "\n\033[1;32mCHANGING HOST!\033[0m\n"
        fun_althost2() {
            sudo sed -i "s;$rmt;remote $rmt2 $_Port;" $cert01
            sudo sed -i "s;$hedr;http-proxy-option CUSTOM-HEADER Host $vivo3;" $cert01
            sudo sed -i "s;$prxy;http-proxy $IP 80;" $cert01
        }
        fun_bar 'fun_althost2'
        echo -e "\n\033[1;32mHOST CHANGED SUCCESSFULLY!\033[0m"
        fun_geraovpn
        sleep 1.5
    elif [[ "$respo" = '3' ]]; then
        echo -e "\n\033[1;32mCHANGING HOST!\033[0m\n"
        fun_althostpay1() {
            sudo sed -i "s;$rmt;remote $rmt2 $_Port;" $cert01
            sudo sed -i "s;$hedr;$payload1;" $cert01
            sudo sed -i "s;$prxy;http-proxy $IP 8080;" $cert01
        }
        fun_bar 'fun_althostpay1'
        echo -e "\n\033[1;32mHOST CHANGED SUCCESSFULLY!\033[0m"
        fun_geraovpn
        sleep 1.5
    elif [[ "$respo" = '4' ]]; then
        echo -e "\n\033[1;32mCHANGING HOST!\033[0m\n"
        fun_althostpay2() {
            sudo sed -i "s;$rmt;remote $rmt2 $_Port;" $cert01
            sudo sed -i "s;$hedr;$payload2;" $cert01
            sudo sed -i "s;$prxy;http-proxy $IP 80;" $cert01
        }
        fun_bar 'fun_althostpay2'
        echo -e "\n\033[1;32mHOST CHANGED SUCCESSFULLY!\033[0m"
        fun_geraovpn
        sleep 1.5
    elif [[ "$respo" = '5' ]]; then
        echo -e "\n\033[1;32mCHANGING HOST!\033[0m\n"
        fun_althost5() {
            sudo sed -i "s;$rmt;remote $rmt3;" $cert01
            sudo sed -i "s;$hedr;http-proxy-option CUSTOM-HEADER Host $IP:$_Port;" $cert01
            sudo sed -i "s;$prxy;http-proxy $prx 80;" $cert01
        }
        fun_bar 'fun_althost5'
        echo -e "\n\033[1;32mHOST CHANGED SUCCESSFULLY!\033[0m"
        fun_geraovpn
        sleep 1.5
    elif [[ "$respo" = '6' ]]; then
        echo -e "\n\033[1;32mCHANGING HOST!\033[0m\n"
        fun_althost6() {
            sudo sed -i "s;$rmt;remote $IP $_Port;" $cert01
            sudo sed -i "s;$hedr;route $IP 255.255.255.255 net_gateway;" $cert01
            sudo sed -i "s;$prxy;http-proxy 127.0.0.1 8989;" $cert01
        }
        fun_bar 'fun_althost6'
        echo -e "\n\033[1;32mHOST CHANGED SUCCESSFULLY!\033[0m"
        fun_geraovpn
        sleep 1.5
    elif [[ "$respo" = '7' ]]; then
        [[ ! -e "$HOME/$username.ovpn" ]] && fun_geraovpn
        echo -e "\n\033[1;32mCHANGING HOST!\033[0m\n"
        fun_packhost() {
            [[ ! -d "$HOME/OVPN" ]] && mkdir $HOME/OVPN
            sudo sed -i "7,9"d $HOME/$username.ovpn
            sleep 0.5
            sudo sed -i "7i\remote $rmt2 $_Port\nhttp-proxy-option CUSTOM-HEADER Host $vivo1\nhttp-proxy $IP 80" $HOME/$username.ovpn
            sudo cp $HOME/$username.ovpn /root/OVPN/$username-vivo1.ovpn
            sudo sed -i "8"d $HOME/$username.ovpn
            sleep 0.5
            sudo sed -i "8i\http-proxy-option CUSTOM-HEADER Host $vivo3" $HOME/$username.ovpn
            sudo cp $HOME/$username.ovpn /root/OVPN/$username-vivo2.ovpn
            sudo sed -i "7,9"d $HOME/$username.ovpn
            sleep 0.5
            sudo sed -i "7i\remote $rmt3\nhttp-proxy-option CUSTOM-HEADER Host $IP:$_Port\nhttp-proxy $prx 80" $HOME/$username.ovpn
            sudo cp $HOME/$username.ovpn /root/OVPN/$username-vivo3.ovpn
            sudo sed -i "7,9"d $HOME/$username.ovpn
            sleep 0.5
            sudo sed -i "7i\remote $IP $_Port\nroute $IP 255.255.255.255 net_gateway\nhttp-proxy 127.0.0.1 8989" $HOME/$username.ovpn
            sudo cp $HOME/$username.ovpn /root/OVPN/$username-bypass.ovpn
            sudo sed -i "7,9"d $HOME/$username.ovpn
            sleep 0.5
            sudo sed -i "7i\remote $rmt2 $_Port\n$payload1\nhttp-proxy $IP 8080" $HOME/$username.ovpn
            sudo cp $HOME/$username.ovpn /root/
