#!/bin/bash
datenow=$(date +%s)
remove_ovp () {
if [[ -e /etc/debian_version ]]; then
	GROUPNAME=nogroup
fi
user="$1"
cd /etc/openvpn/easy-rsa/
sudo ./easyrsa --batch revoke $user
sudo ./easyrsa gen-crl
sudo rm -rf pki/reqs/$user.req
sudo rm -rf pki/private/$user.key
sudo rm -rf pki/issued/$user.crt
sudo rm -rf /etc/openvpn/crl.pem
sudo cp /etc/openvpn/easy-rsa/pki/crl.pem /etc/openvpn/crl.pem
sudo chown nobody:$GROUPNAME /etc/openvpn/crl.pem
[[ -e $HOME/$user.ovpn ]] && sudo rm $HOME/$user.ovpn > /dev/null 2>&1
[[ -e /var/www/html/openvpn/$user.zip ]] && sudo rm /var/www/html/openvpn/$user.zip > /dev/null 2>&1
} > /dev/null 2>&1
echo -e "\E[44;1;37m User          Date         Status         Action   \E[0m"
echo ""
for user in $(awk -F: '{print $1}' /etc/passwd); do
	expdate=$(sudo chage -l $user|awk -F: '/Account expires/{print $2}')
	echo $expdate|grep -q never && continue
	datanormal=$(date -d"$expdate" '+%d/%m/%Y')
	tput setaf 3 ; tput bold ; printf '%-15s%-17s%s' $user $datanormal ; tput sgr0
	expsec=$(date +%s --date="$expdate")
	diff=$(echo $datenow - $expsec|bc -l)
	tput setaf 2 ; tput bold
	echo $diff|grep -q ^\- && echo "VALID   NOT REMOVED" && continue
	tput setaf 1 ; tput bold
	echo "EXPIRED   WAS REMOVED"
	sudo pkill -f $user
	sudo userdel --force $user
	sudo grep -v ^$user[[:space:]] /root/users.db > /tmp/ph ; sudo cat /tmp/ph > /root/users.db
	if [[ -e /etc/openvpn/server.conf ]]; then
		remove_ovp $user
	fi
done
echo '0' > /etc/SSHPlus/Exp
tput sgr0 
echo ""
